apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    k8s-app: apisix-manager-api
    qcloud-app: apisix-manager-api
  name: apisix-manager-api
  # namespace: apisix
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: apisix-manager-api
      qcloud-app: apisix-manager-api
  template:
    metadata:
      labels:
        k8s-app: apisix-manager-api
        qcloud-app: apisix-manager-api
    spec:
      containers:
      - env:
        - name: ENV
          value: prod
        - name: MYSQL_SERVER_ADDRESS
          value: mysql-apisix:3306
        - name: MYSQL_USER
          value: apisix
        - name: MYSQL_PASSWORD
          value: root@123
        - name: APISIX_BASE_URL
          value: http://apisix:80/apisix/admin
        - name: APISIX_API_KEY
          value: edd1c9f034335f136f87ad84b625c8f1
        - name: APISIX_DEBUG_URL
          value: http://apisix:80
        image: yanfengking/apisix-manager-api:latest
        imagePullPolicy: IfNotPresent
        name: manager
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: apisix-manager-api
  # namespace: apisix
spec:
  ports:
  - name: 8080-8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    k8s-app: apisix-manager-api
    qcloud-app: apisix-manager-api
  type: ClusterIP